# Generated by Django 4.0.5 on 2023-02-27 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('publish_status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('survey_date', models.DateField()),
                ('species', models.CharField(choices=[('Sp/sm Chinook', 'Sp/sm Chinook'), ('Fall Chinook', 'Fall Chinook'), ('Coho', 'Coho'), ('Sockeye', 'Sockeye'), ('Steelhead', 'Steelhead')], default='Sp/sm Chinook', max_length=20)),
                ('surveyors', models.CharField(max_length=50)),
                ('survey_type', models.CharField(choices=[('Redd and Carcass', 'Redd and Carcass'), ('Redd', 'Redd'), ('Carcass', 'Carcass')], default='Redd and Carcass', max_length=25)),
                ('survey_method', models.CharField(choices=[('Ground', 'Ground'), ('Helicopter', 'Helicopter'), ('UAV', 'UAV')], default='Ground', max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.activity')),
                ('location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Location')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.protocol')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.task')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activity', '-effective_date', 'active_status'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('row_id', models.IntegerField()),
                ('sample_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='M', max_length=1)),
                ('fork_length', models.IntegerField()),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.parent')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-parent', '-effective_date', 'active_status'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('row_id', models.IntegerField()),
                ('feature', models.CharField(choices=[('Redd', 'Redd'), ('Live Fish', 'Live Fish')], default='Redd', max_length=25)),
                ('count', models.IntegerField()),
                ('wpt_name', models.CharField(max_length=10)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.parent')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-parent', '-effective_date', 'active_status'),
                'abstract': False,
            },
        ),
    ]
