# Generated by Django 4.0.5 on 2023-03-03 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('datasets', '0001_initial'),
        ('data', '0002_rename_feature_child1_feature_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrapHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('publish_status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('trap_date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.activity')),
                ('location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Location')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.protocol')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.task')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activity', '-effective_date', 'active_status'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('row_id', models.IntegerField()),
                ('species', models.CharField(max_length=30)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.activity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activity', '-effective_date', 'active_status'),
                'abstract': False,
            },
        ),
    ]
